export const songs2025 = {
    "Achille Lauro": "Oh… bambina Tutto quello che hai passato è un’università E tuo padre non tornava la sera L’hai visto solo di schiena Lui non sa cosa è stare insieme No, lo so gli vuoi bene L’amore è come una pioggia sopra Villa Borghese E noi stiamo annegando, naufragando è un romanzo Sono solo a fare a botte con gli amici miei Sto strisciando verso il letto e non ci sei Amore mio veramente Se non mi ami muoio giovane Ti chiamerò da un autogrill Tra cento vite o giù di lì Di amore muori veramente Se non ti amo fallo tu per me Ti cercherò in un vecchio film Per sempre noi incoscienti giovani Incoscienti giovani Oh… bambina Dormivamo in un Peugeot Sì noi due ladri di fiori E ti ricordi o no Noi prima A dirsi mai una vita come i tuoi Sì piuttosto disperati come noi Amore mio veramente Se non mi ami muoio giovane Ti chiamerò da un autogrill Tra cento vite o giù di lì Di amore muori veramente Se non ti amo fallo tu per me Ti cercherò in un vecchio film Per sempre noi incoscienti giovani Maledetti giovani (a fumare in quel bar) Noi che a pezzi giovani (noi due pieni di guai) Maledetti, noi incoscienti a dirsi ancora Fammi una carezza amore mio Ma che mi faccia male Mezza sigaretta e dopo addio Per noi incoscienti e giovani Noi due orfanelli alla roulette Siamo a Las Vegas sotto un led Amore mio veramente Se non mi ami muoio giovane Ti chiamerò da un autogrill Per sempre noi incoscienti giovani Incoscienti giovani",
    "Bresh": "Nella tana del granchio c’è una canzone Ho posato i miei vestiti al sole Ti ho vista piangere dietro alle mie parole Ma non sapevo cos’altro dire di te Ora che siamo soli mi puoi pure parlare Guardati intorno non c’è nessuno Non far così non mi giudicare Ho una parola sbagliata per ogni frase Sono soltanto un uomo e non ci so fare E anche se tu non lo vuoi sapere Sappi però che alla ﬁne ti voglio bene Sono una madre che si sgola Una testa che gira ancora Una chitarra che non suona Una borsa piena di buchi Se capisci che non ti amo Sei una sirena che non nuota Cosa puoi dire Fammi solo sapere quando vuoi guarire Dall’espressione hai qualcosa da dire per me Ma lo sento non mi dai due lire Un sacchetto di plastica Tiene i nostri due costumi bagnati Ce li siamo dimenticati Nella macchina che è rimasta sotto al sole per tutta l’estate Ad ottobre li ho ritrovati Lascio la via per te Ora che non è più un sì Camera mia non è una metropoli Che incubo stare ad aspettare in un monolocale Sei fuori a carnevale Sono una madre che si sgola Una testa che gira ancora Una chitarra che non suona Una borsa piena di buchi Se capisci che non ti amo Sei una sirena che non nuota Cosa puoi dire Fammi solo sapere quando vuoi guarire Dall’espressione hai qualcosa da dire per me Ma lo sento non mi dai due lire Se il mare si è salato È perché un marinaio ci ha pianto sopra Se han fatto il calendario È perché ti vorrei fare santa ora Senti che forte il vento Vento che non si posa Cosa puoi dire Fammi solo sapere quando vuoi guarire Dall’espressione hai qualcosa da dire per me Ma lo sento non mi dai due lire Ho bisogno solo di riuscire a convincere te Non solo te Ho bisogno solo di riuscire a convincere te Ma lo sento non mi dai due lire",
    "Brunori Sas": "Sono cresciute veloci le foglie sull’albero delle noci E nei tuoi occhi di mamma adesso splende una piccola fiamma Io come sempre canguro fra il passato e il futuro Scrivo canzoni d’amore alla ricerca di un porto sicuro E come un ragioniere in bilico fra il dare e l’avere Faccio partite doppie persino col mio cuore Come si può cadere in basso Da una distanza siderale Sono passati veloci questi anni feroci E nel mio cuore di padre il desiderio adesso è chiuso a chiave E tu sei stata bravissima all’esame di maturità Ad unire i puntini fra la mia bocca e la verità Che tutto questo amore io non lo posso sostenere Perché conosco benissimo le dimensioni del mio cuore E posso navigare anche in assenza di stella polare Vorrei cambiare la voce Vorrei cantare senza parole Senza mentire Per paura di farti soffrire Vorrei cantarti l’amore, amore Il buio che arriva nel giorno che muore Senza cadere Nella paura di farti male Sono cresciuto in una terra crudele dove la neve si mescola al miele E le persone buone portano in testa corone di spine Ed ho imparato sin da bambino la differenza fra il sangue e il vino E che una vita si può spezzare per un pezzetto di carne o di pane E a tutta questa felicità io non mi posso abituare Perché conosco il sogno del faraone Le vacche grasse e le vacche magre E che si può cadere da una distanza siderale Vorrei cambiare la voce Vorrei cantare senza parole Senza mentire Per paura di farti soffrire Vorrei cantarti l’amore, amore La notte che arriva nel giorno che muore Senza cadere Nella paura di farti male Sono cresciuti troppo veloci questi riccioli meravigliosi E ora ti vedo camminare con la manina in quella di tua madre E tutta questa felicità forse la posso sostenere Perché hai cambiato l’architettura e le proporzioni del mio cuore E posso navigare sotto una nuova stella polare",
    "Clara": "Ti sei preso una parte di me Quella ancora più in fondo dell’anima Un sentimento Che se si rompe taglia Come il vetro E anche deludere È un’abitudine Come nel mio Primo giorno di scuola Non so che faccio qui Il buio è tagliato dalle luci viola Il cielo fa come un glitch Tu mi guardi dall’alto Trascinandomi in basso Non ascolti quando grido Sembri fatto di ghiaccio Io sono fatta così Alle feste chic Sola su un terrazzo Tutti fanno bling bling Io nemmeno mi piaccio Non dire “je t’aime” Dimmelo se Ciò che provi è solo febbre Che sale e scende Che mi fa male male I tuoi occhi Blu Klein Dicono che Stanotte è solo febbre Che sale e scende Tu prendi me Come un enfant per strada In abito da gala Non ci amerà la fama Non cambierà la trama Mille lune passeranno E una ci sarà per sempre Per te che non vuoi scendere Come la febbre Ti sei preso una parte di me Quella ancora più in fondo dell’anima Un sentimento Che se si rompe taglia Come il vetro Corro corro come dentro un bosco Dentro questo inferno è più difficile Questo amore dimmi quanto costa Ti senti un’ombra qua vicino a me Non ascolti quando grido E nemmeno se taccio Non ascolti quando grido Non dire “je t’aime” Dimmelo se Ciò che provi è solo febbre Che sale e scende Che mi fa male male I tuoi occhi Blu Klein Dicono che Stanotte è solo febbre Che sale scende Tu prendi me Come un enfant per strada In abito da gala Non ci amerà la fama Non cambierà la trama Mille lune passeranno E una ci sarà per sempre Per te che non vuoi scendere Come la febbre Mille lune passeranno E una ci sarà per sempre Per te che non vuoi scendere… Non dire “je t’aime” Dimmelo se Ciò che provi è solo febbre Che sale e scende Che mi fa male male I tuoi occhi Blu Klein Dicono che Stanotte è solo febbre Che poi ti prende… Come la febbre Come un enfant per strada In abito da gala Non ci amerà la fama Non cambierà la trama Mille lune passeranno E una ci sarà per sempre Per te che non vuoi scendere Come la febbre",
    "Coma_Cose": "Oggi mi sento una pozzanghera Se l’ansia mi afferra Con lo sguardo verso il cielo Ma il morale per terra Se mi trascuri impazzisco Come maionese Ci sto male, male male male Vorrei svagarmi ma oggi una canzone Dura come un temporale Anche se è molto popolare E mi hai buttato via In un sabato qualunque Mentre andavi in cerca Di uno slancio di modernità Ma tu volevi solo Cuoricini, cuoricini Pensavi solo ai cuoricini, cuoricini Stramaledetti cuoricini, cuoricini Che mi tolgono il gusto di sbagliare tutto Poi mi uccidi, poi mi uccidi Quegli occhi sono due fucili, due fucili Che sparano sui cuoricini, cuoricini Persino sotto alla notizia Crolla il mondo Un divano e due telefoni È la tomba dell’amore Ce l’ha detto anche un dottore Porta un chilo di gelato E poi nel dubbio porta un fiore E almeno un kiss, please E se oggi ho le pupille Più grandi del cuore non mi giudicare Male male male Che dovrei dire io che ti parlavo E tu nemmeno ti mettevi ad ascoltare Tu mettevi solo Cuoricini, cuoricini Pensavi solo ai cuoricini, cuoricini Stramaledetti cuoricini, cuoricini Che mi tolgono il gusto di sbagliare tutto Poi mi uccidi, poi mi uccidi Quegli occhi sono due fucili, due fucili Che sparano sui cuoricini, cuoricini Persino sotto alla notizia Crolla il mondo Ma fortunatamente Un sabato qualunque Mi hai portato via da tutta quanta La modernità Ma dove scappi senza Cuoricini, cuoricini Per l’autostima Cuoricini, cuoricini Che medicina Cuoricini, cuoricini Ma che tolgono il gusto Di sbagliare tutto Poi mi uccidi, poi mi uccidi Quegli occhi sono due fucili, due fucili Che sparano sui cuoricini, cuoricini Persino sotto alla notizia Crolla il mondo Cuoricini, cuoricini Cuoricini, cuoricini Persino sotto alla notizia Crolla il mondo",
    "Elodie": "Quanta gente passa e se ne va Che non sa chi sei Contarla credo sarebbe inutile In un mondo che è freddo oramai Stasera Ci sei solo tu nella città Degli occhi miei Se è vero che poi fanno la ruggine Io non voglio più piangere così (Che cosa ne sai) Prima ancora prima Che ti incontrassi (Amore) Poi rivedersi ancora Come due pazzi (Che cosa mi fai) Travolti da un’idea Che non vuoi che passi Che piano piano scivola giù Dicevi Stasera Dove vai amore Ora che ho bisogno di te Ancora ancora di più Solo per fatalità Insieme Dove vai amore Non mi fai Morire Ancora ancora di più Dimenticarsi alle 7 Dimenticarsi alle 7 Dimenticare Quando prendi a calci la poesia Ma che bella sei Nella tua solitudine Sembra tutto più facile così (Che cosa ne sai) Prima ancora prima Che ti incontrassi (amore) Ancora ancora ancora Come due pazzi (Che cosa mi fai) Travolti da un’idea Che non vuoi che passi Che piano piano scivola giù Dicevi Stasera Dove vai amore Ora che ho bisogno di te Ancora e ancora di più Solo per fatalità Insieme Dove vai amore Non mi fai Morire Ancora ancora di più Dimenticarsi alle 7 Così di un giorno qualunque Mentre si parla di niente Lì seduti in un bar Può capitare a chiunque Mai a noi no Ma che strano eﬀetto che fa Mandare giù La verità Dicevi Stasera Dove vai amore Dove vai Rimani Ancora ancora di più Dimenticarsi alle 7 Dimenticarsi alle 7 Dimenticarsi alle 7 Dimenticarsi alle 7 Dimenticare",
    "Fedez": "Ti porterei in terapia Solo per farti capire, il male che fai Spero che sia un’amnesia Spengo la luce e mi vieni a trovare Fluoxetina, poca saliva Quando mi trovo a parlare di te Sei la carne è viva La mente è schiva Vaga nel buio più buio che c’è Sento un pugno nello stomaco Le paranoie hanno bisogno di troppe attenzioni Forse mento Quando ti dico Sto meglio Stringimi avvolgimi Poi lasciami respirare Seratonina cercasi Illudimi Dentro i miei occhi Guerra dei mondi Tu mi conosci Meglio di me Vorrei guarire Ma non credo Vedo nero pure il cielo Vetri rotti schegge negli occhi Prenditi i sogni Pure i miei soldi Basta che resti lontana da me Vedo il bicchiere Mezzo pieno Con due gocce di veleno Tu mi fotti Respiri corti E aumenta pure il battito, battito Battito, battito Battito, battito, battito, battito, battito accelerato affronto una guerra da disarmato Ho alzato barriere di filo spinato Ma le ho sempre messe nel lato sbagliato Mi sento annullato Dottore che cosa mi ha dato Socialmente accettato Anestetizzato Da un metodo legalizzato Calmati Sto contando i battiti Siamo così fragili Ci feriamo anche sfiorandoci Ti ho odiata te lo giuro Facciamo un po’ ciascuno Basta un po’ di zucchero e va giù pure il cianuro Sento un pugno nello stomaco (nello stomaco) Le paranoie hanno bisogno di troppe attenzioni Forse mento Quando ti dico Sto meglio Dentro i miei occhi Guerra dei mondi Tu mi conosci Meglio di me Vorrei guarire Ma non credo Vedo nero pure il cielo Vetri rotti schegge negli occhi Prenditi i sogni Pure i miei soldi Basta che resti lontana da me Vedo il bicchiere Mezzo pieno Con due gocce di veleno Tu mi fotti Respiri corti E aumenta pure il battito, battito Sembra di galleggiare Sopra ad un mare statico, statico Stringimi avvolgimi Poi lasciami respirare Seratonina cercasi Uccidimi Dentro i miei occhi Guerra dei mondi Tu mi conosci Meglio di me Vorrei guarire Ma non credo Vedo nero pure il cielo Vetri rotti schegge negli occhi Prenditi i sogni Pure i miei soldi Basta che resti lontana da me Vedo il bicchiere Mezzo pieno Con due gocce di veleno Tu mi fotti Respiri corti E aumenta pure il battito, battito Battito, battito",
    "Francesca Michielin": "Dopo centomila lacrime Le grondaie cadono Non so se vorrei rifarlo da capo Quasi speravo tu mi avessi tradito Ti avrei scritto tutto in un messaggio Ma non sapevo se ero in grado Mi hai fatta piangere fuori dallo stadio Ma avrei voluto fosse tutt’altro E va bene E va bene E va bene così Non mi aspetto niente di sensato Come quei cartelli gialli per terra con su scritto “Attenzione! Il pavimento è bagnato” Come se Cambiasse ancora qualcosa così Ci vorrebbe un’altra vita in un film E quanto amore sprecherò Quanti vetri rotti Che sono plastica Per i tuoi stupidi occhi Se non piangi mai Programmare un addio chiusi in macchina Era tutta teoria ma non pratica Mi dispiace però A volte capita Di volersi sempre O mai più Non c’è più il soffitto Chissà con chi farai un figlio Se poi cambierai indirizzo Se c’è fango in paradiso Quante volte mi avrai fatto il cinema Dentro a quel supermercato Non so se l’avevi considerato Che uno dei due sarebbe stato da schifo Ma va bene Va bene Più o meno così Non mi aspetto niente di sensato Da chi l’edera la compra già finta e poi in estate la tiene su un balcone in un vaso Come se Cambiasse ancora qualcosa così Ci vorrebbe un’altra vita E quanto amore sprecherò Quanti vetri rotti Che sono plastica Per i tuoi stupidi occhi Se non piangi mai Programmare un addio chiusi in macchina Era tutta teoria ma non pratica Mi dispiace però A volte capita Di volersi sempre O mai più Non c’è più il soffitto Chissà con chi farai un figlio Se poi cambierai indirizzo Se c’è fango in paradiso Ma non lo so Programmare un addio chiusi in macchina Quasi zero poesia, solo pratica Mi dispiace però A volte capita Di amarsi sempre O mai più Non c’è più il soffitto Chissà se ti vedrò in giro Se avrai perso, se avrò vinto Se c’è fango in Paradiso",
    "Francesco Gabbani": "Ma non lo vedi? E non conta se non ci credi Che siamo un momento Tra sempre e mai più Come una poesia Dentro l’eternità per una botta e via Sarà che una bugia Dice la verità più della verità Ma com’è limpida Com’è domenica Viva la vita così com’è Viva la vita questa vita che È solo un attimo Un lungo attimo Viva la vita finché ce n’è Viva la vita questa vita che È solo un battito Un lungo battito A darsi il cambio Ad aiutarsi A consumarsi al vento Assomigliarsi Pelle e ossa Stesso fuoco dentro Insieme due paralisi faranno un movimento Insieme non si perderanno mai E dimmi una bugia La mezza verità, che tanto poi si sa… Che cosa vuoi che sia Su tutti i lividi farà da anestesia E se ci brucerà E se ci porta via, e se ci porta via Viva la vita così com’è Viva la vita questa vita che È solo un attimo Un lungo attimo Viva la vita finché ce n’è Viva la vita questa vita che È solo un battito Un lungo battito A darsi il cambio Ad aiutarsi A consumarsi al vento Assomigliarsi Pelle e ossa Stesso fuoco dentro Insieme due paralisi faranno movimento Insieme due romantici alle porte dell’inferno Viva la vita così com’è Viva la vita, questa vita che È solo un attimo, un lungo attimo Ma in fondo tu lo sai quello che sento È vivere davvero ogni momento",
    "Gaia": "Per esempio a me piace la musica Stare nuda e nessuno che giudica Amo il cibo di strada I capelli del mare Anche farmi del male Che stupida Menomale che non prende l’Iphone Tra le onde alte di Rio Un silenzio che mi spezza un po’ Che mi brucia un po’ Come fa uno shot E quante parole che Lasciano un vuoto Ti lasciano solo Qualcosa in cui credere Niente di serio se uno dei due se ne va Per una bugia di più Nascosta sotto le labbra Poesia di contrabbando, Ti ricordi quando Era soltanto un gioco Chiamo io chiami tu Chi è il primo che cede stasera Dimmi dove sei Dove dove dove dove Solo io solo tu Tanto non ne vale la pena Chissà dove sei Dove dove dove dove E ogni volta che stiamo così Non serve a niente Tanto è sempre lunedì Lo stesso film Non mi aspettare Non ti scordare Di me mai più Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiama Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiama Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiama Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiama Chiama Come i rami contorti dell’edera Ci aggrappiamo a una scusa ridicola Stiamo qui ad aspettare In un limbo infernale L’amore è una cosa più piccola Cosa rimane se Troppe persone si fottono il cuore A pensare che poi non è Niente di serio se uno dei due se ne va Per una bugia di più Nascosta sotto le labbra Poesia di contrabbando Ti ricordi quando Era soltanto un gioco Chiamo io chiami tu Chi è il primo che cede stasera Dimmi dove sei Dove dove dove dove Solo io solo tu Tanto non ne vale la pena Chissà dove sei Dove dove dove dove E ogni volta che stiamo così Non serve a niente tanto è sempre lunedì Lo stesso film Non mi aspettare Non ti scordare di me Mai più Che pensavo a te Come una voce Che è fragile Come l’idea Di stare con te Volevo stringerti a me Come fosse per sempre ancora Ogni volta che stiamo così Non serve a niente tanto è sempre lunedì Lo stesso film Non mi aspettare Non ti scordare di me Mai più Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiama Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiama Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiama Chiamo io, chiami tu Chiamo io, chiami tu Chiamo io, chiami tu Chiama Chiama",
    "Giorgia": "Dentro la mano una carezza sul viso Senz’anima questo sorriso Che hai cercato, che hai cercato Più ti avvicini e più io mi allontano E i ricordi se ne vanno piano Su e giù come un ascensore Ogni mia stupida emozione E no, non cambierà Dirti una bugia o la verità Per me fare una follia è come la normalità Non so più quante volte ti ho cercato Per quegli occhi, per quegli occhi che fanno da luna Non so più quante notti ti ho aspettato Per finire a ingoiare tutta la paura Di rimanere sola In questa stanza buia Solo tu sei la cura per me Tutto passa Ma scordarti non so ancora come si faccia Qualcosa lo dovevo rovinare Nascondo una lacrima nel mare, ferito Voglio andare avanti all’infinito Trovarti dentro gli occhi di un cane smarrito E no, non cambierà Dirti una bugia o la verità Per me fare una follia è come la normalità Non so più quante volte ti ho cercato Per quegli occhi, per quegli occhi che fanno da luna Non so più quante notti ti ho aspettato Per finire a ingoiare tutta la paura Di rimanere sola In questa stanza buia Solo tu sei la cura per me No che non ho voglia Non ho voglia di rincorrerti Seguire la tua ombra e salire fino sugli alberi Guardando il cielo sapendo che lo stai guardando Ora anche tu Per me sei la luna Per me sei la cura Per me sei avventura Ma non sei nessuno Spengo la paura Di rimanere sola Per quegli occhi Per quegli occhi che fanno da luna Non so più quante notti ho aspettato Per finire a ingoiare tutta la paura Di rimanere sola In questa stanza buia Non sarò mai più sola Per me",
    "Irama": "Non ti ricordi che Sei stata tu crudele, crudele, crudele Fredda come la neve, la neve, la neve Perché era solo una scusa l’idea Che tra noi era soltanto sesso Come se tu Almeno tu Col tuo profumo d’estate Tornassi un attimo E c’è qualcosa che ti agita Smetti di piangere mi guardi che sei fradicia E mi strattoni mentre mi tiri la manica Cerco il tuo sguardo ma ti giri dall’altra parte Ma non so più come dirtelo Vederci appuntamenti nascosti in ristoranti costosi Ma non cambia niente Lentamente si sta spegnendo Ogni fottuto sentimento È meglio fare l’amore se l’amore è un incendio Speravi che i sensi di colpa finissero Ma torneranno quando tornerò E il tuo sorriso mi mastica Ballavi nuda su una canzone classica (na na na) Non te ne accorgi che hai distrutto tutto lentamente Ho distrutto tutto lentamente Tu Almeno tu In quella notte d’estate Tornassi un attimo E c’è qualcosa che ti agita Smetti di piangere mi guardi che sei fradicia E mi strattoni mentre mi tiri la manica Cerco il tuo sguardo ma ti giri dall’altra parte Ma non so più come dirtelo Vederci appuntamenti nascosti in ristoranti costosi Ma non cambia niente Lentamente si sta spegnendo Ogni fottuto sentimento Non vedi che Quando mi guardi davvero negli occhi Non sai se scappare restare Se hai voglia Ma dimmi che sono lontano anni luce Lontano da te E te lo si legge dagli occhi che mi odi E se in amore non soffri, non sogni, non corri, non so innamorarmi di te Lentamente Si sta spegnendo Ogni fottuto sentimento Ogni fottuto sentimento",
    "Joan Thiele": "E ti giuro non ho più bisogno di fingere Questa mia vita è il mio viaggio ed io Traccio da sola le scelte che faccio Ma se ci sei tu Ho più coraggio E ricordo quando eri bambino E restavamo ore abbracciati nel letto Per sentirci grandi e la musica poi ci baciava Per farci sentire un po’ meno soli Forse sarà l’insicurezza Sarà che per noi la famiglia non è mai la stessa Sarà che siamo figli dell’indifferenza Cresciuti da una donna più pura della bellezza E se potessi dirti che Qui la paura non ha età Tu fissala forte dentro gli occhi Spara al centro qui la notte non ci fotte (Bang bang woo) E ti giuro se il tempo è una linea che cambia Sarò la tua eco e poi mai la distanza che corre tra il mondo e le cose Ma se ci sei tu Sì, resto calma Forse sarà l’insicurezza Sarà che per noi la famiglia non è mai la stessa Sarà che siamo figli dell’indifferenza Cresciuti da una donna più pura della bellezza E se potessi dirti che Qui la paura non ha età Tu fissala forte dentro gli occhi Spara al centro qui la notte non ci fotte E se capissi perché contano sempre più le idee Rimangono negli occhi della gente Hanno più potere della rabbia Tu difendile E quando ti senti più fragile Cambia la pelle Equilibrio instabile Fidati è meglio sbagliare che restare immobile E se potessi dirti che Qui la paura non ha età E se capissi perché contano sempre più le idee Rimangono negli occhi della gente Hanno più potere della rabbia Tu difendile (Bang bang woo)",
    "Lucio Corsi": "Volevo essere un duro Che non gli importa del futuro Un robot Un lottatore di sumo Uno spaccino in fuga da un cane lupo Alla stazione di Bolo Una gallina dalle uova d’oro Però non sono nessuno Non sono nato con la faccia da duro Ho anche paura del buio Se faccio a botte le prendo Così mi truccano gli occhi di nero Ma non ho mai perso tempo È lui che mi ha lasciato indietro Vivere la vita È un gioco da ragazzi Me lo diceva mamma ed io Cadevo giù dagli alberi Quanto è duro il mondo Per quelli normali Che hanno poco amore intorno O troppo sole negli occhiali Volevo essere un duro Che non gli importa del futuro no Un robot Medaglia d’oro di sputo Lo scippatore che t’aspetta nel buio Il Re di Porta Portese La gazza ladra che ti ruba la fede Vivere la vita È un gioco da ragazzi Me lo diceva mamma ed io Cadevo giù dagli alberi Quanto è duro il mondo Per quelli normali Che hanno poco amore intorno O troppo sole negli occhiali Volevo essere un duro Però non sono nessuno Cintura bianca di Judo Invece che una stella uno starnuto I girasoli con gli occhiali mi hanno detto “Stai attento alla luce” E che le lune senza buche Sono fregature Perché in fondo è inutile fuggire Dalle tue paure Vivere la vita è un gioco da ragazzi Io Io volevo essere un duro Però non sono nessuno Non sono altro che Lucio Non sono altro che Lucio",
    "Marcella Bella": "Dici che Come me Non ne trovi nessuna Si vabè Poi però Lo ripeti ad ognuna Non ho bisogno di abbracci Mi fanno strano Ma fidati, Lo capisci se ti amo Forte Tosta Indipendente Pelle come diamante Non mi fa male niente Stronza, forse, Ma sorprendente Una mina vagante Sono una combattente Fammi mille complimenti e stop Tanto i miei difetti già li so Forte Tosta Indipendente Non mi tocca niente Ridi e mi Chiami miss E mi provochi in pieno Però poi Dici sì A ogni cosa che chiedo Mi vedi? Star quality Volitiva, niente alibi La mia più grande fan Sono io Forte Tosta Indipendente Pelle come diamante Non mi fa male niente Stronza, Forse, Ma sorprendente Una mina vagante Sono una combattente Fammi mille complimenti e stop Tanto i miei difetti già li so Forte Tosta Indipendente Non mi tocca niente Se ti sembro solo una Voglio dimostrarti che L’altra faccia della luna Non la vedi eppure c’è Ti darò il cuore E se è un errore Mi rende ancora più Forte Tosta Indipendente Pelle come diamante Non mi fa male niente Stronza, Forse, Ma sorprendente Una mina vagante Sono una combattente Fammi mille complimenti e stop Tanto i miei difetti già li so Forte Tosta Indipendente Non mi tocca niente",
    "Massimo Ranieri": "Se hai tra le mani un cuore Un giorno crollerai Sollevalo da terra Comprendilo se torna stanco da una guerra Se hai tra le mani un cuore Tu tienilo in alto E amalo in ginocchio su un altare Che ogni tua ferita lo farà sanguinare La vita intera con il cuore in mare Il mondo l’ha già fatto a pezzi eppure lì rimane Proteggilo dal freddo che c’è stato E troverà la pace dopo quello che ha passato Se hai tra le mani un cuore È come sfidare Dio Consegnalo al suo destino atroce Un bacio come un padre, poi il segno della croce La vita intera con il cuore in mare Il mondo l’ha già fatto a pezzi eppure lì rimane Proteggilo dal freddo che c’è stato E troverà la pace dopo quello che ha passato Tra le mani un cuore Ma non lo puoi vedere Non l’ho mai visto io Neanche quando lo sporcai col rosso di un addio E salverò il tuo cuore in fondo al mare La vita l’ha spezzato e lui continua ad amare Io ti proteggerò da quel che è stato E troverai la pace dopo quello che hai passato Io ti proteggerò da quel che è stato E troverai la pace dopo quello che hai passato Dopo quello che hai passato",
    "Modà": "Convivere con il senso di che sarebbe stato Parlare di coraggio quando sai che non lo hai avuto E camminare in strada con lo sguardo verso il basso Cercando le risposte tra i tuoi passi sull’asfalto E chiedersi se credi davvero in qualche cosa Se non lasciarti andare fa più male o più paura L’ho letto sull’oroscopo che quelli del mio segno Di complicarsi i piani quasi ne hanno un po’ bisogno E non te l’ho mai detto che mentre ti baciavo Tenevo aperti gli occhi e di nascosto ti osservavo Sembravi una canzone che mi squarciava il petto Un quadro di Kandinsky dove immaginarmi tutto Ma è l’ora del ritorno È l’ora del coraggio Forse è vero siamo fatti tutti e due per qualcun altro Ma io non ti dimentico Io no non ti dimentico Difficile accettarlo Ma non siamo più gli stessi Difficile convivere tra tutti quei ricordi Che sanno di passione Che sanno di rimpianti Che sanno di carezze date al buio mentre dormi Chissà se ti ricordi La mia prima domanda Dicesti non ti posso dare ora una risposta Eppure lo sapevi Ma non volevi dirlo Soltanto per paura Soltanto per orgoglio E non te l’ho mai detto che mentre ti baciavo Tenevo aperti gli occhi e di nascosto ti osservavo Sembravi una canzone che mi squarciava il petto Un quadro di Kandinsky dove immaginarmi tutto Ma è l’ora del ritorno È l’ora del coraggio Forse è vero siamo fatti tutti e due per qualcun altro Ma io no non ti dimentico Io no non ti dimentico E non te l’ho mai detto che mentre ti baciavo Tenevo aperti gli occhi e di nascosto ti osservavo Sembravi una canzone che mi squarciava il petto Un quadro di Kandinsky dove immaginarmi tutto È l’ora del ritorno È l’ora del coraggio Forse è vero siamo fatti tutti e due per qualcun altro Io no non ti dimentico Ma io no non ti dimentico",
    "Noemi": "Scusa è tardi, se vuoi passo da te, Siamo stanchi, di lasciare sempre perdere, Non rispondi se ti chiedo d’accendere, Avere figli non è, non è, Un discorso facile da prendere. Perché in fondo sai, che se, sto qua, Ti stringerei fino ad odiarti ma lo so, Che non è facile, lasciarsi perdere, serenamente. Perché è impossibile scordare quelle notti, Con i sorrisi e con le borse sotto gli occhi, La sensazione che se ti innamori muori, Serenamente. Credo sia normale, farsi continuamente dei pensieri strani, Se inizia a svanire, la magia che c’era siamo già alla fine. Perché non è più la prima volta, che prendi un treno per vedermi, Che abbiamo l’ansia se si allungano i silenzi. Perché in fondo sai, che se, sto qua, Ti stringerei fino ad odiarti ma lo so, Che non è facile, lasciarsi perdere, serenamente. Perché è impossibile scordare quelle notti, Con i sorrisi e con le borse sotto gli occhi, La sensazione che se ti innamori muori, Serenamente. Lasciami soltanto un’altra via d’uscita, Da questa discussione che sembrava infinita, Qualcuno dovrà perdere, perché, Accettarsi è difficile, quando non sai qual è la strada da prendere, Dire siam diversi è sempre dura da ammettere, Lasciami perdere, se conosci il peggio di me. Perché in fondo sai, che se, sto qua, Ti stringerei fino ad odiarti ma lo so, Che non è facile, lasciarsi perdere, serenamente. Perché è impossibile scordare quelle notti, Con i sorrisi e con le borse sotto gli occhi, La sensazione che se ti innamori muori, Serenamente.",
    "Olly": "Magari non sarà Nemmeno questa sera La sera giusta per tornare insieme Tornare a stare insieme Magari non sarà Nemmeno questa sera Me l’ha detto la signora, là aﬀacciata al quarto piano Con la sigaretta in bocca, Mentre stendeva il suo bucato Io le ho risposto che Vorrei Vorrei Vorrei Vorrei Vorrei Vorrei Tornare a quando Ci bastava Ridere, piangere, fare l’amore E poi stare in silenzio per ore Fino ad addormentarci sul divano Con il telecomando in mano Non so più come fare senza te Te che mi fai, vivere e dimenticare, Tu che mentre cucini ti metti a cantare E tu chiamala se vuoi la ﬁne Ma come te lo devo dire Sta vita non è vita senza te Ma sai che questa sera Balorda nostalgia Mi accendo la tv Solo per farmi compagnia Che bella tiritera… Beh insomma Ti sembra la maniera Che vai e mi lasci qua Ti cerco ancora in casa quando mi prude la schiena E metto ancora un piatto in più quando apparecchio a cena So soltanto che vorrei, Vorrei Vorrei Vorrei Sì vorrei Vorrei Tornare a quando Ci bastava Ridere, piangere, fare l’amore E poi stare in silenzio per ore Fino ad addormentarci sul divano Con il telecomando in mano Non so più come fare senza te Te che mi fai, vivere e dimenticare, Tu che mentre cucini ti metti a cantare E tu chiamala se vuoi la ﬁne Ma come te lo devo dire Sta vita non è vita senza te Ma chissà perché Oh, sta vita non è vita senza te Magari non sarà Magari è già ﬁnita Però ti voglio bene Ed è stata tutta vita",
    "Rkomi": "Dove sono i soldi adesso Che sei rimasta sola? Pornograﬁa ma senza sesso Eﬀetto senza droga Dov’è il tuo Dio? Pensavo poveri poveri noi Non sono problemi tuoi Il caos non sciopera mai Ovunque prende forma Ultimamente fumo ed esco Veramente poco Sto in mutande mentre fisso Stupidamente il vuoto Ancora e poi di nuovo Finché l’alba va via dalla via Non mi è più chiaro se sia Musica o burocrazia Questo caos che forma Il ritmo delle cose Il ritmo che ci muove Ci corre nella gola Ci spezza le parole È il ritmo delle cose E ti stancherai come fai coi vestiti Mi romperai come i tuoi giochi preferiti Quante cose distruggiamo costruendo È un violento decrescendo È un moderno decrescendo È un inferno a fuoco lento Amore senza sentimento È un violento decrescendo E ti stancherai come fai coi vestiti Mi romperai come i tuoi giochi preferiti Quante cose distruggiamo costruendo È un violento decrescendo Si può fermare la pioggia Ma è inutile scomodare i cieli Se in quelle macchie di Rorschach Ci vedo cose, le più crudeli Buttati nel mondo, siamo alla prova Come si lancia per caso un bouquet da sposa Esco da un’altra festa, esco dall’algoritmo Ritrovo la bellezza solo dietro l’imprevisto È caos che corre Che lento muore Il ritmo delle cose Il ritmo che ci muove Ci corre nella gola Ci spezza le parole È il ritmo delle cose E ti stancherai come fai coi vestiti Mi romperai come i tuoi giochi preferiti Quante cose distruggiamo costruendo È un violento decrescendo È un moderno decrescendo È un inferno a fuoco lento Amore senza sentimento È un violento decrescendo E ti stancherai come fai coi vestiti Mi romperai come i tuoi giochi preferiti Quante cose distruggiamo costruendo È un violento decrescendo Forse solo la stanchezza Ti porta dentro quella stanza Che hanno chiamato libertà Di dire no, di dire basta Questo casino mi somiglia È il lato oscuro in piena vista O è forse merda di un artista È il ritmo delle cose Il ritmo che ci muove Ci corre nella gola Ci spezza le parole È il ritmo delle cose E ti stancherai come fai coi vestiti Mi romperai come i tuoi giochi preferiti Quante cose distruggiamo costruendo È un violento decrescendo È un moderno decrescendo È un inferno a fuoco lento Amore senza sentimento È un violento decrescendo E ti stancherai come fai coi vestiti Mi romperai come i tuoi giochi preferiti Quante cose distruggiamo costruendo È un violento decrescendo",
    "Rose Villain": "Cosa fai Mentre tutti dormono? Chissà se mi pensi o no Mentre la luna cala su di noi Splende in alto, guarda Mai una volta giudica Nostalgia puttana Sono sola come lei Che cosa fai Mentre tutti sognano? Ma forse ho oltrepassato il limite di ore senza te Sento il tuo nome e inizia a piovere fuori e dentro me Mi rigiro nel letto, non dormo più Vorrei saperti dire di no C’è quel film che ti piaceva alla TV Sembra che stia parlando di noi Se pensarti fosse un crimine stanotte io sarei Fuorilegge Fuorilegge Partiamo domani Bonnie e Clyde Coi sogni rubati Senza di me Cosa fai? Mentre tutti si amano Io rido del nostro destino avverso Ascolto Almeno Tu nell’Universo Mi inginocchio e chiedo agli angeli di darmi ciò che ho perso Ma forse ho oltrepassato il limite di ore senza te Sento il tuo nome e inizia a piovere fuori e dentro me Mi rigiro nel letto, non dormo più Vorrei saperti dire di no C’è quel film che ti piaceva alla TV Sembra che stia parlando di noi Se pensarti fosse un crimine stanotte io sarei Fuorilegge Fuorilegge Partiamo domani Bonnie e Clyde Coi sogni rubati Senza di me Cosa fai? Forse non sai che per te ho pianto Stelle sopra al soffitto però io mi accontento Canzoni tristi dal primo piano Cuori a 200 all’ora ma vuoi ballare un lento Forse ho oltrepassato il limite di ore senza te Sento il tuo nome e inizia a piovere fuori e dentro me Mi rigiro nel letto, non dormo più Vorrei saperti dire di no C’è quel film che ti piaceva alla TV Sembra che stia parlando di noi E se pensarti fosse un crimine stanotte io sarei Fuorilegge",
    "Sarah Toscano": "La sera ride, ma suona drammatica Sembra la zona più buia di un luna park Con te era più romantica La ruota panoramica Mi piaceva anche avere paura C’è un vento che mi porterà Mi scioglierà le trecce Di una vie en rose come Édith Piaf Non mi rimane niente C’ero io, c’eri tu Una lacrima mi scende Anche se ti scorderò In un club il sabato È tutto così amarcord, Comico e tragico Cosa eri tu, non lo so Ma un po’ mi avevi illusa Sai però Forse in un film io con te Non mi c’immagino Sembra così démodé, però era magico Cosa sei tu, un déjà vu Mi sono solo illusa Amarcord Una lama mi accarezza la consapevolezza Che indietro non ci ritornerò E mi faccio tenerezza Un velo di tristezza è l’unico vestito che ho C’è un vento che mi porterà Mi scioglierà le trecce Di una vie en rose come Édith Piaf Non mi rimane niente C’ero io, c’eri tu Una lacrima mi scende Anche se ti scorderò in un club il sabato È tutto così amarcord, comico e tragico Cosa eri tu, non lo so Ma un po’ mi avevi illusa Sai però Forse in un film io con te Non mi c’immagino Sembra così démodé, però era magico Cosa sei tu, un déjà vu Mi sono solo illusa Amarcord E ancora quel ricordo stupendo Non è volato via con il vento Ma dopo tutto mi arrendo Una lacrima mi scende giù Anche se ti scorderò È tutto così amarcord Cosa eri tu, non lo so Ma un po’ mi avevi illusa Illusa, illusa Anche se ti scorderò in un club il sabato È tutto così amarcord, comico e tragico Cosa eri tu, non lo so Ma un po’ mi avevi illusa Sai però Forse in un film io con te Non mi c’immagino Sembra così démodé, però era magico Cosa sei tu, un déjà vu Mi sono solo illusa Amarcord",
    "Serena Brancale": "Ti penso tra le vie E quando vedo le scie Delle barche in questo mare. Carpe diem, Domani le tue bugie Non le voglio più ascoltare. La mia anima canta, È una camicia bianca Che mi sventola addosso. (Oh eh) Stanotte saremo due stelle del cinema, Italo-americano. Dammi un bacio su un taxi cabrio, Un bacio Che s’adda veré, s’adda da veré, s’adda da veré. Baby I love u, Nenné ti amo, Non lo so se ti suonerà neo-melodico, Ma stanotte ti dedico: Anema e core. A A A, Perché metti questa cassa dritta? Io con te vorrei ballare salsa, Tipo soli soli sulla Rambla Maria Callas canta! (Lazzì) Cosa vuoi davvero, soldi o libertà? Che ti saluti dal balcone la città? L’eleganza viene dal basso, come il jazz. Stanotte saremo due stelle del cinema, Italo-americano. Dammi un bacio su un taxi cabrio, Un bacio Che s’adda veré, s’adda da veré, s’adda da veré. Baby I love u, Nenné ti amo, Non lo so se ti suonerà neo-melodico, Ma stanotte ti dedico: Anema e core, Anema e core, Anema e core, Anema e core. Italo-americano. Dammi un bacio su un taxi cabrio, Un bacio Che s’adda veré, s’adda da veré, s’adda da veré. (Brà) Pccè io e tè Sim na cosa sola, Sim du facce della stessa luna. Com sta collana che porta fortuna, Bra ù sà, marioul. Nan zi dann’ adenza a nsciun’. Tu sta cummè p’ fa l’amore, Io vogghj attè, anema e core. Italo-americano. Dammi un bacio su un taxi cabrio, Un bacio Che s’adda veré, s’adda da veré, s’adda da veré. Baby I love u, Nenné ti amo, Non lo so se ti suonerà neo-melodico, Ma stanotte ti dedico: Anema e core, Anema e core, Anema e core, Anema e core. Italo-americano, Dammi un bacio su un taxi cabrio, Un bacio Che s’adda veré, s’adda da veré, s’adda da veré. Lazzì",
    "Shablo": "È una street song Per dare quello che ho Brucerò fino alla fine Chiuso tra cemento e smog È una street song Qui la gente muore e vive Senza soldi e alternative L’unica cosa che so 24h 7 su 7 no stop Siamo in sbatti sbatti per arrivare al top Tu fai chatty chatty io faccio parlare il mio flow Non ti danno abbracci qua sei da solo nel block Io le mando baci lei che per me è la più hot Mi dicevi taci, ora però sono il goat Quaggiù odi e ami a giudicarmi è Dio Amo la mia mami, amo sti money e l’hip-hop È una street song Per dare quello che ho Brucerò fino alla fine Chiuso tra cemento e smog È una street song Qui la gente muore e vive Senza soldi e alternative L’unica cosa che so Suona dal basso questo gospel È la voce di chi raccoglie le forze Nonostante tutto mette da parte i forse qui vince la legge del più forte È rap è blues e gin & juice Fai il mio nome tre volte beetlejuice Suona ancora più forte bad and boujee Rock’n’roll lo sai party & bullshit La voce del blocco suonerà più forte Per quelle volte che ci hanno chiuso le porte E ho solo una word, se dico che hai la mia parola Lo sanno i miei g, questa è la way that we live È una street song Per dare quello che ho Brucerò fino alla fine Chiuso tra cemento e smog È una street song Qui la gente muore e vive Senza soldi e alternative L’unica cosa che so È una street song Per dare quello che ho Brucerò fino alla fine Chiuso tra cemento e smog È una street song Qui la gente muore e vive Senza soldi e alternative L’unica cosa che so",
    "Simone Cristicchi": "Quando sarai piccola ti aiuterò a capire chi sei, Ti starò vicino come non ho fatto mai. Rallenteremo il passo se camminerò veloce, Parlerò al posto tuo se ti si ferma la voce. Giocheremo a ricordare quanti figli hai, Che sei nata il 20 marzo del ’46. Se ti chiederai il perché di quell’anello al dito Ti dirò di mio padre ovvero tuo marito. Ti insegnerò a stare in piedi da sola, a ritrovare la strada di casa. Ti ripeterò il mio nome mille volte perché tanto te lo scorderai. Eeee… è ancora un altro giorno insieme a te, Per restituirti tutto quell’amore che mi hai dato E sorridere del tempo che non sembra mai passato. Quando sarai piccola mi insegnerai davvero chi sono, A capire che tuo figlio è diventato un uomo. Quando ti prenderò in braccio E sembrerai leggera come una bambina sopra un’altalena. Preparerò da mangiare per cena, io che so fare il caffè a malapena. Ti ripeterò il tuo nome mille volte fino a quando lo ricorderai. Eeee… è ancora un altro giorno insieme a te, Per restituirti tutto, tutto il bene che mi hai dato. E sconfiggere anche il tempo che per noi non è passato. Ci sono cose che non puoi cancellare, Ci sono abbracci che non devi sprecare. Ci sono sguardi pieni di silenzio Che non sai descrivere con le parole. C’è quella rabbia di vederti cambiare E la fatica di doverlo accettare. Ci sono pagine di vita, pezzi di memoria Che non so dimenticare. Eeee… è ancora un altro giorno insieme a te, Per restituirti tutta questa vita che mi hai dato E sorridere del tempo e di come ci ha cambiato. Quando sarai piccola ti stringerò talmente forte Che non avrai paura nemmeno della morte Tu mi darai la tua mano, io un bacio sulla fronte Adesso è tardi, fai la brava Buonanotte.",
    "The Kolors": "Persa in un’isola grande così A mille miglia da questa città Avevi grandi occhi neri e mi fa Dove stai andando? Non lo so Era una stella che lascia una scia Un desiderio che nasce così La gente in strada che viene e che va Si sta cercando E non lo sa Tutte le storie sono uguali e te lo dico C’è sempre uno che se ne va da Roma a Portorico Mi sento come l’ultima bottiglia che ho nel frigo Che non ricordo mai mai mai mai Mi piaci un minimo Mi aspetti a Mykonos In ogni rendez-vous Bugie si dicono Chi non è libero Chi non c’ha il fisico Stasera non importa più Tu con chi fai l’amore E perché Sale come un ascensore quando vengo da te Se fai così mi togli l’anima Che cosa stupida Tanto la cosa importante non è Tu con chi fai l’amore Stasera Domani Chissà Tu con chi fai l’amore Stasera Domani Chissà A mezzanotte poi un salto nel blu Dove le luci si spengono già Diceva dai l’hai capito anche tu Mi sto innamorando Non lo so Io per gli errori c’ho una mezza calamita Chi prova le emozioni e chi le compra con la visa Non mi mandare fuori appena inizia la partita Con te non gioco mai mai mai mai Mi piaci un minimo Mi aspetti a Mykonos In ogni rendez-vous Bugie si dicono Chi non è libero Chi non c’ha il fisico Stasera non importa più Tu con chi fai l’amore E perché Sale come un ascensore quando vengo da te Se fai così mi togli l’anima Che cosa stupida Tanto la cosa importante non è Tu con chi fai l’amore Non posso spegnere le luci dell’alba Che sono dentro la stanza Guarda che confusione Non c’è mai una ragione Uhh Non posso credere alle voci dell’ansia Sanno il mio nome ma non è la realtà Guarda che confusione Ma non importa più (Tu con chi fai) (Tu con chi fai) Tu con chi fai l’amore E perché Sale come un ascensore quando vengo da te Se fai così mi togli l’anima Che cosa stupida Tanto la cosa importante non è Tu con chi fai l’amore Stasera Domani Chissà Tu con chi fai l’amore Stasera Domani Chissà",
    "Tony Effe": "Io non soffro per te Non so fare l’attore Sono pronto a sbagliare Come un uomo d’onore Spengo la sigaretta Come la nostra storia Ogni notte è per sempre Per le strade di Roma E non fare la stupida stasera Tu non sei mai sincera Tu sei pericolosa Io so che morderai la mela Ma di noi cosa direbbe Califano Che è durato troppo poco Cammino sui sanpietrini Fino a quando non te trovo Damme ‘na mano Che c’ho ner core Solo ‘na donna e ‘na canzone Nun conta niente Si crolla er monno Io m’aricordo solo di te Damme ‘na mano Sinno me moro Damme ‘na mano Che c’ho ner core Soltanto te Io e te per tutta la vita Te lo giuro mi incrocio le dita Sono il classico uomo italiano Amo solo mia madre Annarita La domenica ti lascio sola Vuoi andare a cena ma c’è la partita Tu mi aspetti nel letto nervosa Parli poco fai la stranita Poi mi tocchi te ne fotti Vai più giù mi si girano gli occhi Poi mi guardi togli i tacchi Mentre ti fai i capelli raccolti A te piace sbagliare farmi del male Mi alzi le mani Poi ti vuoi scusare E so che perderò questo gioco Come a carte sei brava a barare Damme ‘na mano Che c’ho ner core Solo una donna E ‘na canzone Non conta niente Si crolla er monno Io m’aricordo solo di te Damme ‘na mano Sinno me moro Damme ‘na mano Che c’ho ner core Soltanto te Io ho sofferto per te Ora so fare l’attore Quante volte ho sbagliato Come un uomo d’onore Accendo la sigaretta Penso alla nostra storia Mentre guardo la notte Per le strade di Roma",
    "Willie Peyote": "Ma che storia triste avevo aspettative basse E sai già come finisce visto da dove si parte Tu vorresti che la gente ti capisse la ami come se lei ricambiasse E c’hai provato anche più volte dei Jalisse ma l’insistenza non è mai così di classe Certi discorsi vanno presi con le pinze oppure provocano risate grasse E te la aspetti ma ogni volta ti stupisce, guarda le loro facce come se non bastasse Grazie ma no grazie Tanto fanno finta ma lo sanno Più e profondo e meno paga quasi sempre meglio stare in superficie Salvagente Le risposte che ti danno sembran fatte con lo stampo Quindi metterò le mani avanti due passi indietro ogni passo avanti Dovresti andare a lavorare e non farti manganellare nelle piazze Grazie ma no grazie Questa gente non fa un cazzo li mantengo tutti io con le mie tasse Grazie ma no grazie Dovresti dare meno ascolto ai sentimenti che non sono mai dei buoni investimenti Dovremmo organizzare una rimpatriata tipo una cena di classe Grazie ma no grazie Grazie ma no Davvero grazie ma C’è chi non sa più come scrivere non sa come parlare Non sa a quali parole deve mettere ad esempio l’asterisco al plurale C’è chi non sa più come ridere non sa come scherzare E vuole la tradizione se la confusione qua è generale Eh oggi va così chissà domani Domani domani domani magari riesco a capire gli esseri umani Chi bacia sulla bocca i propri figli e c’è chi bacia sulla bocca i propri cani E quanto va di moda il vittimismo di chi attacca ma dice che si difende C’è chi dice non si può più dire niente poi invece parla sempre almeno sii coerente Almeno per sta volta che c’è chi ancora ti da corda E c’è chi ha perso la memoria e vorrebbe che tornasse come se non bastasse Grazie ma no grazie Dovresti andare a lavorare e non farti manganellare nelle piazze Grazie ma no grazie Questa gente non fa un cazzo li mantengo tutti io con le mie tasse Grazie ma no grazie Dovresti dare meno ascolto ai sentimenti che non sono mai dei buoni investimenti Dovremmo organizzare una rimpatriata tipo una cena di classe Grazie ma no grazie Grazie ma no Davvero, grazie ma no Storia triste aspettative basse C’è chi sparisce finché si calmano le acque (ma che storia triste) C’è chi annuisce tra le frasi fatte vince chi stupisce sempre a mani basse Grazie ma no grazie Grazie ma no Davvero grazie ma no grazie",
    "Rocco Hunte": `
        Mi ricordo una strada
Un quartiere qualunque
Un bambino che sogna
Pure se non ha niente
Ogni giorno è un regalo
Per chi come me è destinato a partire
E le voci di chi ha giudicato
Ritornano nella mia testa
Mi dicevano tu non sarai mai nessuno
E ora non mi ricordo più, com’è l’odore del caffè
Quelle canzoni che mamma ascoltava alla radio
Giocavamo in quartiere sembrava uno stadio
Non è stata domenica mai più
Da quando sono andato via da casa mia,
Rimpiango anche le cose che odiavo
Le stesse che mi hanno fatto andare via
L’erba cresce in un campetto abbandonato
Colpa dei telefoni non ci hanno più giocato
L’ansia nel cuore quando le citofonavo
Se rispondeva il padre poi scappavo
Lo stato è assente come noi in mezzo a quei banchi
Un foglio bianco dove scriverò mi manchi
Tutto quello che ti serve è nel quartiere
Studia oppure ‘mparate ‘o mestiere
E mo’ riportami dove
Overamente songo je
‘O cafè dint’‘e canzone
Viento ‘e mare che sbatte pe’ dinto ‘e feneste
Me sceta ‘e po’ se ne va
Me vonno fottere l’anema
Ma je ‘ccu poco sto buono
Doje prete pe fa’ ‘na porta
Turnasse criaturo pe’ correre
Mille vote ancora
E ridere
Mille vote ancora
E chiagnere
Mille vote ancora
‘A casa mia
Mille vote ancora
Faccio brutti sogni e po’ me sceto ‘e botto
Vedo le facce degli amici ca nun ce stanno cchiù
Aggio sbagliato a prendermi le colpe
A pensare: potevo fare di più
Ad immaginare ‘nu finale diverso
A pensa’ si chella palla nun pigliava ‘a traversa
A distinguere l’amore dal sesso
Se ‘o posto ‘e vencere avesse perso, fosse rimasto me stesso
Il nemico a volte è l’orgoglio
Che chiude rapporti anche se non c’è un motivo
Siamo carte stropicciate nel portafoglio
Siamo anime buone in mondo cattivo
Perciò dicimme: tutt’appost’
Anche quando il mondo cade sulle spalle nostre
Anche quando alle domande non c’è una risposta
A campà accussì è tosta
Era meglio ‘a casa nostra
E mo’ riportami dove
Overamente songo je
‘O cafè dint’‘e canzone
Viento ‘e mare che sbatte pe’ dinto ‘e feneste
Me sceta ‘e po’ se ne va
Me vonno fottere l’anema
Ma je ‘ccu poco sto buono
Doje prete pe fa’ ‘na porta
Turnasse criaturo pe’ correre
Mille vote ancora
E ridere
Mille vote ancora
E chiagnere
Mille vote ancora
‘A casa mia
Mille vote ancora
Se mi vedi un po’ triste è perché cocche vota
Me manca assaje mamma mia, ‘a casa mia
Dove ancora si muore per niente a vent’anni
‘Sti figlie anna capi’
‘Sta guerra adda ferni’
E mo’ riportami dove
Overamente songo je
‘O cafè dint’‘e canzone
Viento ‘e mare che sbatte pe’ dinto ‘e feneste
Me sceta ‘e po’ se ne va
Me vonno fottere l’anema
Ma je ‘ccu poco sto buono
Doje prete pe fa’ ‘na porta
Turnasse criaturo pe’ correre
Mille vote ancora
E ridere
Mille vote ancora
E chiagnere
Mille vote ancora
‘A casa mia
Mille vote ancora
    `,
};